[tools]
action-validator = "latest"
editorconfig-checker = "latest"
markdownlint-cli2 = "latest"
prek = "latest"
taplo = "latest"
uv = "latest"

[tasks."docs:serve"]
description = "Serving Docs"
run = "uv run mkdocs serve"

[tasks."docs:build"]
description = "Building Docs"
run = "uv run mkdocs build --clean"
